### PR TITLE
Merge latest upstream into develop branch

### PR DESCRIPTION
**Pull request by vinograd47**
Some MLIR changes which I personally find interesting for our project:

* [Introduce "encoding" attribute to tensor type](https://github.com/llvm/llvm-project/commit/7714b405a0de47e461c77fa8dbd2c21f0d34bbf2)
* [Add support for walking locations similarly to Operations](https://github.com/llvm/llvm-project/commit/706c9c5ce0382644d4e693741f5d885be7c20e46)
* [Pass AnalysisManager as optional parameter to analysis ctor](https://github.com/llvm/llvm-project/commit/cd94f18ec1ba5b5c0e19e9c7506b1de86651354a)
* [Add a new C++ LSP server for MLIR named mlir-lsp-server](https://github.com/llvm/llvm-project/commit/751c14fc4218e26426007f61725f673bee4e08be)
* [Add a vscode language extension for MLIR](https://github.com/llvm/llvm-project/commit/b810e3a552e2e0b66052370878d7885344469320)
* [Canonicalize AllocOp's with only store and dealloc uses](https://github.com/llvm/llvm-project/commit/f22d3813850f9e87c5204df6844a93b8c5db7730)
* [Introduce attribute interface/attribute for tensor encoding](https://github.com/llvm/llvm-project/commit/23c9e8bc25795b69e16d39b674c19c79a2bb107b)
* [Debug log IR after pattern applications](https://github.com/llvm/llvm-project/commit/6176a8f90961ce39b0a7c97e2f8891cd1ada61a3)
* [Add a utility method to get reassociations maps for reshape](https://github.com/llvm/llvm-project/commit/a6e09391bbe7cb42d591f2a8c169cf4e8980e121)
* [Use ReassociationIndices instead of affine maps in linalg.reshape](https://github.com/llvm/llvm-project/commit/2865d114f953a0c05df2663f4569704c9fe35eb0)
* [Add a pattern to bufferize linalg.tensor_reshape](https://github.com/llvm/llvm-project/commit/a3f22d020b2709b2b4897ae3450c33834e646329)
* [Factor pass timing out into a dedicated timing manager](https://github.com/llvm/llvm-project/commit/33f908c42881fa02963f0c64f8be5088717664cc)
* [Add a helper function to convert LogicalResult to int for return from main](https://github.com/llvm/llvm-project/commit/58369fce30af484889356f225d89cb0b32009206)

Local `check-mlir` run:

```
[build] -- Testing: 969 tests, 12 workers --
[build] Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
[build] 
[build] Testing Time: 13.71s
[build]   Unsupported: 177
[build]   Passed     : 792
[build] Build finished with exit code 0
```

### CODE REVIEW

**Comment by vinograd47** [comment]
@flaub @jbruestle @earhart I'm not sure, what is the process of our fork alignment with the upstream.

**Comment by flaub** [comment]
@vinograd47 We'll need to update PlaidML to account for all of these changes. Can you take a stab at doing that?

**Comment by vinograd47** [comment]
@flaub I'm afraid I can't do this. I am not familiar with Affine dialect and as I can see locally, there was some changes in upstream regarding its operation, which causes build issues for the PlaidML. For some part I don't know the semantic of old methods and don't know how to map them to the new API.

**Comment by vinograd47** [comment]
Or at least could you please assist me? As I can see, there were some changes in `AffineParallelOp` operation.

First, it now takes `lbMaps` and `ubMaps` as array of `AffineMap`, not a single `AffineMap`. I've added a workaround for this by passing array with single element. Hoping it doesn't break the semantic of the operation. Second, new attribute was added (`ArrayRef<int64_t> steps`). I'm passing empty array for it. This changes fixes the compilation, but I'm not sure if they are valid.

Another issue, `getRangesValueMap` method seems to be removed from `AffineParallelOp`. And I don't know what it the replacement for it. @flaub Could you please help me with this?

**Comment by flaub** [comment]
@vinograd47 I'm using a branch so that I can have a commit that can be used for testing in our CI: https://github.com/plaidml/llvm-project/pull/39

**Comment by vinograd47** [comment]
@flaub Great, thanks! I'm closing my PR in favor to your.

**Pull request closed without merging**
